---
- hosts: prod-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy insureme application
    command: sudo docker run -itd -p 8083:8081 --name insure-me sunildh123/insureme:1.0